#18 Homepage with a map of multiple locations
way-seoul/on-my-way pull request #48
Opened 2023-01-17 10:18 UTC by polarbearTW

-Hide API key from the code
-Set username & password on httpd configuration file
-A GMap with sample locations from the database

2023-01-17 10:23 UTC, hjusassac commented
could you edit the readme file as well,  please?

2023-01-17 10:36 UTC, polarbearTW commented
> could you edit the readme file as well, please?

Hi Hyeonju, I just did, please check, thanks!

2023-01-19 11:24 UTC, LEMON4DE approved these changes, later dismissed

2023-01-19 11:35 UTC, LEMON4DE requested changes

2023-01-19 11:35 UTC, LEMON4DE commented on public/styles.css
> +<<<<<<< HEAD
```suggestion
```

2023-01-19 11:35 UTC, LEMON4DE commented on public/styles.css
> +=======
```suggestion
```

2023-01-19 11:35 UTC, LEMON4DE commented on public/styles.css
> +>>>>>>> 94af5a58af6de069fa86df3ab26eb69441c2c21f
```suggestion
```

2023-01-19 11:35 UTC, LEMON4DE commented on controller/controllerHelper.php
> +}
```suggestion
        if($validated == true){
            $_SESSION['logged_in'] = true;
        }
        
        $logged_in = isset($_SESSION['logged_in']) && $_SESSION['logged_in'];
        
        return $logged_in;
    }
}
```

2023-01-19 11:50 UTC, LEMON4DE approved these changes

2023-01-19 11:51 UTC, merged